addSbtPlugin("org.jetbrains"  % "sbt-ide-settings" % "1.1.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"     % "2.4.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"     % "0.9.25")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"          % "2.0.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"     % "3.9.5")